CartPhill/Controllers/OPPsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CartPhill.Models;

namespace CartPhill.Controllers
{
    public class OPPsController : Controller
    {
        private Product db = new Product();

        // GET: OPPs
        //public ActionResult Index()
        //{
        //    return View(db.Hoards.ToList());
        //}
        public ActionResult Index(string productCatagory, string searchString)
        {
            var CatagoryList = new List<string>();
            var CatagoryQuery = from d in db.Hoards
                orderby d.Catagory
                select d.Catagory;

            CatagoryList.AddRange(CatagoryQuery.Distinct());
            ViewBag.productCatagory = new SelectList(CatagoryList);

            var products = from p in db.Hoards
                           select p;
            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(s => s.Name.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(productCatagory))
            {
                products = products.Where(k => k.Catagory == productCatagory);
            }
            return View(products);
        }

        // GET: OPPs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OPP oPP = db.Hoards.Find(id);
            if (oPP == null)
            {
                return HttpNotFound();
            }
            return View(oPP);
        }

        // GET: OPPs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OPPs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Price,Description,Catagory")] OPP oPP)
        {
            if (ModelState.IsValid)
            {
                db.Hoards.Add(oPP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(oPP);
        }

        // GET: OPPs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OPP oPP = db.Hoards.Find(id);
            if (oPP == null)
            {
                return HttpNotFound();
            }
            return View(oPP);
        }

        // POST: OPPs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Price,Description,Catagory")] OPP oPP)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oPP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(oPP);
        }

        // GET: OPPs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OPP oPP = db.Hoards.Find(id);
            if (oPP == null)
            {
                return HttpNotFound();
            }
            return View(oPP);
        }

        // POST: OPPs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OPP oPP = db.Hoards.Find(id);
            db.Hoards.Remove(oPP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

CartPhill/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CartPhill.Models;
using CartPhill.ViewModels;

namespace CartPhill.Controllers
{
    public class ShoppingCartController : Controller
    {
        Product storeDB = new Product();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            return View(viewModel);
        }

        public ActionResult AddToCart(int id)
        {
            var addedOpp = storeDB.Hoards
                .Single(opps => opps.Id == id);
            var cart = ShoppingCart.GetCart(this.HttpContext);//dets for adding
            cart.AddToCart(addedOpp);//opp added to cart
            return RedirectToAction("Index");//return for more shopping
        }
        // Here comes the AJAX- Remove from cart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            string ProductName = storeDB.Carts.Single(item => item.RecordId == id).product.Name;
            int itemCount = cart.RemoveFromCart(id);
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(ProductName) +
                          " has been thrown back into the void from which it came",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //GET; /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

CartPhill/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CartPhill</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CartPhill", "Index", "OPPs", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li>@Html.ActionLink("Shop", "Index", "OPPs")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Cart", "Index", "ShoppingCart")</li>

                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CartPhill - All Rights Reserved and Retained.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/Scripts")
</body>
</html>